//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oa_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorityUser
    {
      
        public int id { get; set; }
      
        public string name { get; set; }
      
        public string loginName { get; set; }
      
        public string password { get; set; }
      
        public string email { get; set; }
      
        public string phone { get; set; }
      
        public bool isDisable { get; set; }
      
        public string address { get; set; }
      
        public string remark { get; set; }
      
        public string picture { get; set; }
      
        public bool isDelete { get; set; }
      
        public System.DateTime createTime { get; set; }
    }
}
